#!/bin/bash
# https://github.com/insanum/gcalcli
# display a 5 day agenda based on my google calendar
# use daily from cron

msg=$(gcalcli --nocolor --nostarted agenda)

if [ "$1" == '-n' ] ; then
    notify-send -u critical 'Agenda' "$msg"
else
    echo "$msg"
fi