#!/bin/sh
# update my iplayer db tables
# moodfarm@cpan.org

date >> /tmp/get_iplayer_update.log
# we know we have some scripts 
PATH=$PATH:$HOME/bin

# update iplayer
export SQLFILE="$HOME/.get_iplayer/iplayer.sqlite3"
export IPLAYER="$HOME/.get_iplayer/tv.cache"
export HISTORY=/tmp/history.$$.csv

# update the podcast db
#get_iplayer --type=podcast 1>&2 > /dev/null
# replace double quotes for single quotes so that csv import does not mess up
# cat $HOME/.get_iplayer/podcast.cache | tr -d '"' | tr -d  "'" | txt2db -c --delimitor='|' podcast,- |sqlite3 $SQLFILE

# update the radio db
get_iplayer --type=radio 1>&2 > /dev/null
# replace double quotes for single quotes so that csv import does not mess up
#cat $HOME/.get_iplayer/radio.cache |  tr -d '"' | tr -d  "'" | txt2db -c --delimitor='|' radio,- |sqlite3 $SQLFILE

# now do the TV
get_iplayer 1>&2 > /dev/null
# update the db
# replace double quotes for single quotes so that csv import does not mess up
cat $IPLAYER |  tr -d '"' | tr -d  "'" | txt2db -c --delimitor='|' tv,- |sqlite3 $SQLFILE

# update the with the history, needs a header first
echo "pid|name|short_desc|type|added|quality|stored_to|default_field|duration|desc|channel|categories|thumbnail|adult|url|episode" >$HISTORY
# replace double quotes for single quotes so that csv import does not mess up
cat $HISTORY $HOME/.get_iplayer/download_history | tr -d '"' | tr -d "'" | txt2db -c --delimitor='|' downloads,- |sqlite3 $SQLFILE

# create the views
sqlite3 $SQLFILE "DROP VIEW IF EXISTS download_names ;
    CREATE VIEW IF NOT EXISTS download_names AS
    SELECT pid, CASE
    WHEN 
        (instr( name, ':')) != 0 THEN substr( name, 0, instr( name, ':'))
    ELSE 
        name
    END AS 'name' from downloads ;"

sqlite3 $SQLFILE "DROP VIEW IF EXISTS tv_names ;
    CREATE VIEW IF NOT EXISTS tv_names AS
    SELECT tv._index, pid, CASE
    WHEN 
        (instr( name, ':')) != 0 THEN substr( name, 0, instr( name, ':'))
    ELSE 
        name
    END AS 'name' from tv ;"

# and the view of things to record
sqlite3 $SQLFILE "DROP VIEW IF EXISTS record_list ;
    CREATE VIEW IF NOT EXISTS record_list AS
    SELECT DISTINCT t._index,t.name,t.pid from tv_names as t, download_names as d
    WHERE 
        t.name = d.name 
    and 
        t.pid NOT IN (SELECT pid from downloads);"

#        t.pid NOT IN (SELECT pid from download_names);"


# update the DBIx::Class schema
cd ~/src/lib
dbicdump Iplayer::Schema dbi:SQLite:$SQLFILE 2>/dev/null
