#!/bin/sh
# run a perl script under a debugger
# moodfarm@cpan.org
# basic console debugger - I am rubbish with this
# perl -d $*

PERL5LIB=$PERL5LIB:./lib

# as cannot get the .Xdefaults/.Xresources to work, lets go for the alternative
export PTKDB_CODE_FONT='-*-clean-*-*-*-*-*-150-*-*-*-*-*-*'
# export PTKDB_CODE_FONT='-schumacher-*-*-*-*-*-*-160-*-*-*-*-*-*'
# export PTKDB_CODE_FONT='-*-*-*-*-*-*-*-140-*-*-*-*-*-*'
export PTKDB_EVAL_FONT="$PTKDB_CODE_FONT"
export PTKDB_CODE_SIDE='right'
export PTKDB_SCROLLBARS_ONRIGHT=1
DEBUGGER=ptkdb
# DEBUGGER=hdb
# DEBUGGER=tkdb
# DEBUGGER=Trepan

if [ "$DEBUGGER" = "hdb" ] ; then
    # for the web based debugger
    PORT=9876
    perl -d:hdb=port:$PORT $* &
    sleep 2
    # and open a webpage for it with your default browser
    x-www-browser http://localhost:$PORT/debugger-gui 2>/dev/null
else
    perl -d:$DEBUGGER $*
fi




