#!/bin/bash
# simple progress bar
# moodfarm@cpan.org

# make sure not to do any other printing while using this :)

MARKER=">"
PADDING=""

function show_usage() {
    echo "display a percentage bar
$0 current_counter_value max_counter_value
"
    exit 1 
}

function progress_bar() {
    WIDTH=$1
    current=$2
    max=$3
    echo "PERCENT=$(($current / $max))"
    PERCENT=$(($current / $max))
 
    while [ $PERCENT -lt $(($WIDTH+1)) ]
    do  
        echo -ne "\r\t[ "
        echo -ne "$PADDING$MARKER ] $((PERCENT*100/$WIDTH))% "
        PADDING="${PADDING}="
        # let PERCENT=$PERCENT+1
    done
}
 

width=50
current=$1
max=$2

if [ "$current" == "" ] ; then
    show_usage
fi

if [ "$max" == "" ] ; then
    show_usage
fi


progress_bar $width $current $max