#!/bin/sh
# queue up things for later retrival from BBC get_iplayer
# moodfarm@cpan.org

# get fantasy radio shows from radio 4 extra
# matches=`get_iplayer --type=radio --channel=extra --category=fantas |ack  '^\d+:'|awk -F':' '{print $1}'`

# for match in `get_iplayer --type=radio --channel=extra --category=fantas 2>/dev/null |ack  '^\d+:'|awk -F':' '{print $1}'`
# do
#     # get_iplayer --type=radio -g "$match"
#     get_iplayer --type=radio --pvr- "$match"
# done

# RADIO things
# add all matched files to the record queue
get_iplayer --type=radio --category=scifi --search=.* --pvr-queue >/dev/null
get_iplayer --type=radio pratchett --pvr-queue >/dev/null
get_iplayer --type=radio "The Infinite Monkey Cage" "in our time" --pvr-queue >/dev/null
get_iplayer --type=radio "hitchhiker's" --pvr-queue >/dev/null

# TV things
get_iplayer --pvr-queue "Family Guy" "American Dad" --pvr-queue >/dev/null
get_iplayer --pvr-queue "the crimson field" "monkey planet" "mountain gorilla" "planet earth" "the living planet" "wild wales"
get_iplayer --pvr-queue "the plantagenets" "jamaica inn" "hinterland"
get_iplayer --pvr-queue "doctor who" "sherlock" "salamander" "The Musketeers" "atlantis" "wallance and gromit" --pvr-queue >/dev/null
get_iplayer --pvr-queue "rome" "egypt"  "romans" "ancient greece" --pvr-queue >/dev/null
get_iplayer --pvr-queue "hairy bikers" "life of rock" "wild china"  "infested" "dissected" "secrets of bones" "The Fantastical World of Hormones" --pvr-queue >/dev/null

get_iplayer_db
