#!/bin/bash
filepath="$1"


function check_version() {
  fname=$1

  version=`grep -E '^version: ' $fname | awk '{print $2}'`
  if [ "$version" != "" ] ; then
    grep -qE "^$version [0-9]{4}-[0-9]{2}-[0-9]{2}" $fname
    if [ "$?" != "=" ] ; then
      echo "ERROR: Could not find version number and release date"
    fi
  fi
}

echo "$filepath" |grep -Eq '\.md$'
if [ "$?" == "0" ] ; then
  # should we write it to a PDF dir
  b=`dirname $filepath`
  f=`basename $filepath .md`
  PDF="$b/PDF"
  DOC="$b/docs"
  if [ -d "$PDF" ] ; then
    OUTPUT="-o $PDF"
  else
    if [ -d "$DOC" ] ; then
      OUTPUT="-o $DOC"
    else
      OUTPUT="$f.pdf"
    fi
  fi



  check_version $filepath


  OUT=`ct2 -p -c "$filepath" -v $OUTPUT`
  echo "Procesed to $OUT"
fi
