#!/usr/bin/env perl
# simple script to listen to zmq events coming from salt and reporting on them
# moodfarm@cpan.org
# work in progress - not wotking

use strict;
use warnings;

use ZMQ::LibZMQ3;
use ZMQ::Constants qw(ZMQ_PULL ZMQ_REP ZMQ_SUB ZMQ_SUBSCRIBE ZMQ_DONTWAIT);

#use zhelpers;
use Data::Printer;

use constant MAX_MSGLEN => 255;

my $SALT = '/var/run/salt/master/master_event_pull.ipc';

# or is it master_event_pull.ipc ?? or publish_pull.ipc or workers.ipc?

#my $context = zmq_init;

## zmq_connect( $socket, "ipc://$SALT" );

#my $subscriber = zmq_socket($context, ZMQ_PULL);
#zmq_connect($subscriber, 'tcp://localhost:4505' );
##zmq_setsockopt($subscriber, ZMQ_SUBSCRIBE, '10001');

#while (1) {
#        my $buf;
#        my $size = zmq_recv($subscriber, $buf, MAX_MSGLEN, ZMQ_DONTWAIT);
#        if ($size != -1) {
#            print "salt: " . Dumper( $buf) . "\n" ;
#        }
#    }

my $ctxt = zmq_init();
my $parent_sock = zmq_socket( $ctxt, ZMQ_PULL );
zmq_bind( $parent_sock, "ipc://$SALT" );
while (1) {
    my $msg  = zmq_recvmsg($parent_sock);
    my $data = zmq_msg_data($msg);
    print "salt: " . p($data) . "\n";
}
