#!/usr/bin/env python
# taken from https://gist.github.com/yuvipanda/10481205
# Simple script that converts yaml files into json files while
# also preserving the order of any dictionary structures
# used in the yaml file
import sys
import yaml
import collections
import json

# Setup support for ordered dicts so we do not lose ordering
# when importing from YAML
_mapping_tag = yaml.resolver.BaseResolver.DEFAULT_MAPPING_TAG


def dict_representer(dumper, data):
    return dumper.represent_mapping(_mapping_tag, data.iteritems())


def dict_constructor(loader, node):
    return collections.OrderedDict(loader.construct_pairs(node))

yaml.add_representer(collections.OrderedDict, dict_representer)
yaml.add_constructor(_mapping_tag, dict_constructor)

data = yaml.load(open(sys.argv[1]))
print json.dumps(data, indent=2)